# Generated by Django 4.0.6 on 2022-07-13 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Введите тип новости', max_length=25, verbose_name='Тип новости')),
            ],
            options={
                'verbose_name_plural': 'Типы новостей',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите email', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Электронные почты рассылки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите оглавление новости', max_length=45, verbose_name='Оглавление')),
                ('date_of_creation', models.DateField(default=datetime.date.today, help_text='Введите дату создания новости')),
                ('text_content', models.TextField(help_text='Введите содержание новости', verbose_name='Содержание')),
                ('type', models.ForeignKey(help_text='Выберите тип новости', on_delete=django.db.models.deletion.PROTECT, to='blog.newstype', verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'ordering': ['title', 'type'],
            },
        ),
    ]
