# Generated by Django 4.1 on 2023-02-02 21:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('blogscholar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogscholar')),
                ('en_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter news content', verbose_name='English content')),
                ('uk_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter news content', verbose_name='Ukrainian content')),
            ],
            bases=('blog.blogscholar',),
        ),
    ]
