# Generated by Django 4.1 on 2022-09-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['en_title', 'uk_title', 'type', 'date_of_creation'], 'verbose_name_plural': 'News'},
        ),
    ]
