# Generated by Django 4.1 on 2023-02-21 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='en_title',
            field=models.CharField(help_text='Enter news title', max_length=100, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Slug', unique=True, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='uk_title',
            field=models.CharField(help_text='Enter news title', max_length=100, verbose_name='Ukrainian title'),
        ),
    ]
