# Generated by Django 4.1 on 2022-10-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='policy_area',
            field=models.ForeignKey(default='Foreign policy', help_text='Choose policy area', on_delete=django.db.models.deletion.PROTECT, to='blog.policyarea', verbose_name='Policy area'),
        ),
        migrations.AlterField(
            model_name='policyarea',
            name='name',
            field=models.CharField(help_text='Enter policy area name', max_length=25, unique=True, verbose_name='Policy area name'),
        ),
    ]
