# Generated by Django 4.0.6 on 2022-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, help_text='Введіть дату створення новини', verbose_name='Дата створення'),
        ),
    ]
