# Generated by Django 4.1 on 2024-07-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogscholar',
            name='details_image',
            field=models.ImageField(default=1, upload_to='uploads/blog-scholars/details-images', verbose_name='Details page image'),
            preserve_default=False,
        ),
    ]
