# Generated by Django 4.0.6 on 2022-07-14 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title', 'type'], 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name_plural': 'Типи новин'},
        ),
        migrations.AlterModelOptions(
            name='useremail',
            options={'verbose_name_plural': 'Електронні пошти розсилки'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_creation',
            field=models.DateField(default=datetime.date.today, help_text='Введіть дату створення новини', verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_content',
            field=models.TextField(help_text='Введіть зміст новини', verbose_name='Зміст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Введіть заголовок новини', max_length=45, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(help_text='Оберіть тип новини', on_delete=django.db.models.deletion.PROTECT, to='blog.newstype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='type',
            field=models.CharField(help_text='Введіть тип новини', max_length=25, verbose_name='Тип новини'),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(help_text='Введіть email', max_length=254, unique=True),
        ),
    ]
