# Generated by Django 4.1 on 2023-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='type',
            field=models.CharField(choices=[('Opinion', 'Opinion'), ('Events', 'Events'), ('News', 'News'), ('Op-eds', 'Op-eds'), ('Analytics', 'Analytics')], help_text='Enter news type', max_length=25, unique=True, verbose_name='News type'),
        ),
    ]
