# Generated by Django 4.1 on 2023-02-21 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_en_title_alter_article_uk_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Slug', unique=True, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
