# Generated by Django 4.1 on 2024-12-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogscholar_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='interviewer',
            field=models.ForeignKey(blank=True, help_text='Select an interviewer if needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.blogscholar', verbose_name='Interviewer'),
        ),
    ]
