# Generated by Django 4.0.6 on 2022-08-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_date_of_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введіть email', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Електронні пошти розсилки',
            },
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_creation',
            field=models.DateField(default=datetime.date.today, help_text='Введіть дату створення новини', verbose_name='Дата створення'),
        ),
    ]
