# Generated by Django 4.1 on 2022-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='mailing_language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], default='en', max_length=2),
        ),
    ]
