# Generated by Django 4.1 on 2023-02-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_en_title_alter_article_uk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogscholar',
            name='slug',
            field=models.SlugField(default='slug', help_text='Slug', unique=True),
            preserve_default=False,
        ),
    ]
