# Generated by Django 4.0.6 on 2022-07-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options_alter_newstype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(default='News', help_text='Оберіть тип новини', on_delete=django.db.models.deletion.PROTECT, to='blog.newstype', verbose_name='Тип'),
        ),
    ]
