# Generated by Django 4.1 on 2023-02-24 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_en_title_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_of_creation', 'type', 'en_title'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['email'], 'verbose_name_plural': 'Subscribers e-mails'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_of_creation', 'type'], 'verbose_name_plural': 'Video content'},
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
    ]
