# Generated by Django 4.1 on 2023-02-02 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(help_text='Select an author if needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.teammember', verbose_name='Author'),
        ),
    ]
