# Generated by Django 4.0.6 on 2022-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscription_delete_useremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введіть email', max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Електронні пошти розсилки',
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
