# Generated by Django 4.1 on 2023-04-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_libraryresource_file_alter_subresource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryresource',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
