# Generated by Django 4.1 on 2023-02-24 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_news_options_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=200, verbose_name='Higher Education or Research Institution')),
                ('department', models.CharField(max_length=200, verbose_name='Research Unit/Department/Chair')),
                ('education_level', models.CharField(choices=[('1', 'Master'), ('2', 'Doctor or PhD'), ('3', 'Postgraduate'), ('4', 'Doctorate')], max_length=1, verbose_name='Level of education')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_of_creation', 'en_title']},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog Articles'},
        ),
        migrations.AlterModelOptions(
            name='blogscholar',
            options={'verbose_name_plural': 'Blog Scholars'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date_of_creation']},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-date_of_creation', 'email'], 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='en_full_name',
            field=models.CharField(help_text='Enter full name on english', max_length=45, verbose_name='Full name on english'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uk_full_name',
            field=models.CharField(help_text='Enter full name on ukrainian', max_length=45, verbose_name='Full name on ukrainian'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(help_text='Enter e-mail', max_length=255, unique=True),
        ),
    ]
