# Generated by Django 4.1 on 2023-04-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_libraryresource_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryauthor',
            name='en_full_name',
            field=models.CharField(help_text='Enter full name on english', max_length=45, unique=True, verbose_name='Full name on english'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Only for Books.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='blog.libraryauthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='file',
            field=models.FileField(blank=True, help_text='Only for Books, Brochures and other.', null=True, upload_to='uploads/resources', verbose_name='Resource file'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='pages',
            field=models.PositiveIntegerField(blank=True, help_text='Only for Books.', null=True),
        ),
    ]
