# Generated by Django 4.0.6 on 2022-07-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_news_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text_content',
        ),
    ]
