# Generated by Django 4.1 on 2022-08-21 17:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', ckeditor_uploader.fields.RichTextUploadingField(help_text='Введіть зміст відео', verbose_name='Зміст')),
            ],
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name_plural': 'Електронні пошти підписників'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(help_text='Введіть email', max_length=254, unique=True),
        ),
    ]
