# Generated by Django 4.1 on 2023-04-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_libraryauthor_en_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subresource',
            name='cover',
        ),
    ]
