# Generated by Django 4.1 on 2023-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_subscriber_email_alter_subscriber_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymember',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ORCHID/Google Scholar'),
        ),
        migrations.AddField(
            model_name='librarymember',
            name='resource_plans',
            field=models.TextField(default=123, max_length=600, verbose_name='Resource Plans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarymember',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Academic CV'),
        ),
        migrations.AddField(
            model_name='librarymember',
            name='specialization',
            field=models.CharField(default=123, max_length=200, verbose_name='Scientific Specialization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarymember',
            name='supervisor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Academic Supervisor/Cosultant'),
        ),
        migrations.AlterField(
            model_name='librarymember',
            name='education_level',
            field=models.CharField(choices=[(1, 'Master'), (2, 'Doctor or PhD'), (3, 'Postgraduate'), (4, 'Doctorate')], max_length=1, verbose_name='Level of education'),
        ),
        migrations.AlterField(
            model_name='librarymember',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone number'),
        ),
    ]
