# Generated by Django 4.1 on 2023-02-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_slug'),
        ('blog', '0006_librarymember_google_scholar_and_more'),
    ]

    operations = [
    ]
