# Generated by Django 4.1 on 2022-08-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_video_delete_useremail_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Відеоконтент'},
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='confirmed',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='conf_num',
        ),
    ]
