# Generated by Django 4.1 on 2023-02-26 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20230226_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarymember',
            options={'ordering': ['-date_of_creation', 'last_name'], 'verbose_name_plural': 'Library members'},
        ),
        migrations.AddField(
            model_name='librarymember',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
    ]
