# Generated by Django 4.1 on 2023-04-15 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_libraryauthor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymember',
            name='specialization_code',
            field=models.PositiveIntegerField(default=123, validators=[django.core.validators.MinValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='en_title',
            field=models.CharField(help_text='Enter video title', max_length=100, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uk_title',
            field=models.CharField(help_text='Enter video title', max_length=100, verbose_name='Ukrainian title'),
        ),
    ]
