# Generated by Django 4.1 on 2023-02-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_librarymember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymember',
            name='education_level',
            field=models.CharField(choices=[('1', 'Master'), ('2', 'Doctor or PhD'), ('3', 'Postgraduate'), ('4', 'Doctorate')], max_length=1, verbose_name='Level of education'),
        ),
    ]
