# Generated by Django 4.1 on 2022-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_news_options_video_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
