# Generated by Django 4.1 on 2023-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_librarymember_specialization_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyarea',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
