# Generated by Django 4.1 on 2022-09-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_news_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='This is some subtitle', help_text='Введіть текст підзаголовку', max_length=1000, verbose_name='Підзаголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(upload_to='banners/', verbose_name='Банер новини'),
        ),
    ]
