# Generated by Django 4.1 on 2023-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_librarymember_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymember',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
