# Generated by Django 4.1 on 2023-07-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_policyarea_slug_alter_person_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryauthor',
            options={'verbose_name_plural': 'Library authors'},
        ),
        migrations.AlterModelOptions(
            name='libraryresource',
            options={'verbose_name_plural': 'Library resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name_plural': 'Resource types'},
        ),
        migrations.AlterModelOptions(
            name='subresource',
            options={'verbose_name_plural': 'Subresources'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('order',), 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
