# Generated by Django 4.1 on 2023-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_policyarea_slug_alter_person_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryauthor',
            options={'verbose_name_plural': 'Library authors'},
        ),
        migrations.AlterModelOptions(
            name='libraryresource',
            options={'verbose_name_plural': 'Library resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name_plural': 'Resource types'},
        ),
        migrations.AlterModelOptions(
            name='subresource',
            options={'verbose_name_plural': 'Subresources'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogscholar',
            name='slug',
            field=models.SlugField(default='blog-scholar-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default='team-member-slug', unique=True),
            preserve_default=False,
        ),
    ]
