# Generated by Django 4.1 on 2023-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_libraryauthor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogscholar',
            options={'ordering': ('order',), 'verbose_name_plural': 'Blog Scholars'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('order',), 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='blogscholar',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
