# Generated by Django 4.1 on 2023-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_librarymember_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymember',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='librarymember',
            name='supervisor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Academic Supervisor/Consultant'),
        ),
    ]
