# Generated by Django 4.1 on 2022-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_news_subtitle_alter_news_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.TextField(help_text='Введіть текст підзаголовку', max_length=1000, verbose_name='Підзаголовок'),
        ),
    ]
