# Generated by Django 4.1 on 2022-09-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_news_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='content',
        ),
    ]
