# Generated by Django 4.1 on 2023-07-17 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogscholar_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMember',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.person')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('en_name', models.CharField(help_text='Enter name', max_length=100, verbose_name='English name')),
                ('uk_name', models.CharField(help_text='Enter name', max_length=100, verbose_name='Ukrainian name')),
                ('banner', models.ImageField(upload_to='uploads/general-members', verbose_name='Member banner')),
                ('link', models.URLField(help_text='Enter link', verbose_name='Member link')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name_plural': 'General Members',
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('blog.person', models.Model),
        ),
    ]
