# Generated by Django 4.1 on 2023-03-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20230301_1937'),
        ('blog', '0011_alter_librarymember_password_and_more'),
    ]

    operations = [
    ]
