# Generated by Django 4.1 on 2023-03-27 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_20230302_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.article')),
                ('type', models.CharField(choices=[('journals', 'Journals'), ('magazines', 'Magazines'), ('books', 'Books'), ('newspapers', 'Newspapers'), ('brochures', 'Brochures'), ('other', 'Other papers')], default='journals', max_length=20)),
                ('banner', models.ImageField(upload_to='uploads/library_banners', verbose_name='News banner')),
            ],
            bases=('blog.article',),
        ),
        migrations.AlterField(
            model_name='librarymember',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Library Members Resumes', verbose_name='Academic CV'),
        ),
        migrations.AlterField(
            model_name='news',
            name='en_subtitle',
            field=models.TextField(help_text='Enter subtitle', max_length=100, verbose_name='English subtitle'),
        ),
        migrations.AlterField(
            model_name='news',
            name='uk_subtitle',
            field=models.TextField(help_text='Enter subtitle', max_length=100, verbose_name='Ukrainian subtitle'),
        ),
        migrations.CreateModel(
            name='LibrarySubresource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/resources', verbose_name='Resource file')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of creation')),
                ('bounded_resource', models.ForeignKey(help_text='Choose bounded resource', on_delete=django.db.models.deletion.CASCADE, to='blog.libraryresource', verbose_name='Bounded resource')),
            ],
        ),
    ]
