# Generated by Django 4.1 on 2023-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_generalmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmember',
            name='is_rounded',
            field=models.BooleanField(default=False),
        ),
    ]
