# Generated by Django 4.1 on 2023-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_libraryresource_alter_librarymember_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysubresource',
            name='topic',
            field=models.CharField(default=123, help_text='Enter topic', max_length=45, verbose_name='Topic'),
            preserve_default=False,
        ),
    ]
