# Generated by Django 4.1 on 2023-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_generalmember_is_rounded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='type',
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='en_name',
            field=models.CharField(default='Books', max_length=50),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='uk_name',
            field=models.CharField(default='Книги', max_length=50),
        ),
    ]
