# Generated by Django 4.1 on 2023-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_librarysubresource_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysubresource',
            name='file',
            field=models.FileField(upload_to='uploads/resources', verbose_name='Resource file'),
        ),
    ]
