# Generated by Django 4.1 on 2023-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_resourcetype_type_resourcetype_en_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='en_subtitle',
            field=models.TextField(help_text='Enter subtitle', max_length=200, verbose_name='English subtitle'),
        ),
        migrations.AlterField(
            model_name='news',
            name='uk_subtitle',
            field=models.TextField(help_text='Enter subtitle', max_length=200, verbose_name='Ukrainian subtitle'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='en_name',
            field=models.CharField(default='Books', help_text='Enter English name', max_length=50, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='uk_name',
            field=models.CharField(default='Книги', help_text='Enter Ukrainian name', max_length=50, verbose_name='Ukrainian name'),
        ),
    ]
