# Generated by Django 4.1 on 2023-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_librarysubresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryresource',
            name='type',
            field=models.CharField(choices=[('Journals', 'Journals'), ('Magazines', 'Magazines'), ('Books', 'Books'), ('Newspapers', 'Newspapers'), ('Brochures', 'Brochures'), ('Other papers', 'Other papers')], default='Journals', max_length=20),
        ),
    ]
