# Generated by Django 4.1 on 2023-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_librarysubresource_bounded_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysubresource',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/resource_covers', verbose_name='Subresource cover'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='banner',
            field=models.ImageField(upload_to='uploads/library_banners', verbose_name='Resource banner'),
        ),
    ]
