# Generated by Django 4.1 on 2023-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_librarysubresource_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysubresource',
            name='topic',
            field=models.CharField(help_text='Enter topic', max_length=45, unique=True, verbose_name='Topic'),
        ),
    ]
